// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/estate-revenue-current/CurrentAppointments.tsx": () => import("../components/mockups/estate-revenue-current/CurrentAppointments.tsx"),
  "./components/mockups/estate-revenue-current/CurrentAutomations.tsx": () => import("../components/mockups/estate-revenue-current/CurrentAutomations.tsx"),
  "./components/mockups/estate-revenue-current/CurrentLeads.tsx": () => import("../components/mockups/estate-revenue-current/CurrentLeads.tsx"),
  "./components/mockups/estate-revenue-current/CurrentOverview.tsx": () => import("../components/mockups/estate-revenue-current/CurrentOverview.tsx"),
  "./components/mockups/estate-revenue-current/CurrentReports.tsx": () => import("../components/mockups/estate-revenue-current/CurrentReports.tsx")
};
